[package]
name = "orbterm"
description = "The Orbital Terminal"
repository = "https://github.com/redox-os/orbterm"
version = "0.3.2"
license = "MIT"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[[bin]]
name = "orbterm"
path = "src/main.rs"

[dependencies]
orbclient = "0.3"
orbfont = "0.1"
ransid = "0.4"

[target.'cfg(not(target_os = "redox"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_termios = "0.1"
redox_syscall = "0.1"
